{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avatargo.fullname" . }}-{{ .Values.database.component }}-deploy
  labels:
    {{- include "avatargo.labels" . | nindent 4 }}
    component: {{ .Values.database.component }}
spec:
  replicas: {{ .Values.database.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "avatargo.selectorLabels" . | nindent 6 }}
      component: {{ .Values.database.component }}
  template:
    metadata:
      labels:
        {{- include "avatargo.selectorLabels" . | nindent 8 }}
        component: {{ .Values.database.component }}
    spec:
      containers:
        - name: {{ include "avatargo.fullname" . }}-{{ .Values.database.component }}
          image: {{ .Values.database.image }}
          envFrom:
            - configMapRef:
                name: {{ include "avatargo.fullname" . }}-{{ .Values.database.component }}-cf        #Имя конфигмапы которая подключится к поду
            - secretRef:
                name: {{ include "avatargo.fullname" . }}-{{ .Values.database.component }}-scrt      #Имя секрета который подключится к поду
          resources:                        #Ресурсы
            limits:                         #Предел исползования ресурсов контейреном, при привышении CPU - тротлинг, при превышении памяти - рестрат
              cpu: {{ .Values.database.resources.limits.cpu }}
              memory: {{ .Values.database.resources.limits.memory }}
            requests:                       #Минимально необходимые ресурсы для выделения контейнеру. Кубер будет искать ноды с этими ресурсами
              cpu: {{ .Values.database.resources.requests.cpu }}
              memory: {{ .Values.database.resources.requests.memory }}
{{- end }}