{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatargo.fullname" . }}-{{ .Values.database.component }}-srvc
  labels:
    {{- include "avatargo.labels" . | nindent 4 }}
    component: {{ .Values.database.component }}
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: {{ include "avatargo.name" . }}
    component: {{ .Values.database.component }}
  ports:
    - name: database
      port: {{ .Values.database.port | default 5432 }}
      targetPort: {{ .Values.database.port | default 5432 }}
      protocol: TCP
{{- end }}