{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avatargo.fullname" . }}-{{ .Values.grafana.component }}-deploy
  labels:
    {{- include "avatargo.labels" . | nindent 4 }}
    component: {{ .Values.grafana.component }}
spec:
  replicas: {{ .Values.grafana.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "avatargo.selectorLabels" . | nindent 6 }}
      component: {{ .Values.grafana.component }}
  template:
    metadata:
      labels:
        {{- include "avatargo.selectorLabels" . | nindent 8 }}
        component: {{ .Values.grafana.component }}
    spec:
      containers:
        - name: {{ include "avatargo.fullname" . }}-{{ .Values.grafana.component }}
          image: {{ .Values.grafana.image }}
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ include "avatargo.fullname" . }}-{{ .Values.grafana.component }}-cf        #Имя конфигмапы которая подключится к поду
          resources:                        #Ресурсы
            limits:                         #Предел исползования ресурсов контейреном, при привышении CPU - тротлинг, при превышении памяти - рестрат
              cpu: {{ .Values.grafana.resources.limits.cpu }}
              memory: {{ .Values.grafana.resources.limits.memory }}
            requests:                       #Минимально необходимые ресурсы для выделения контейнеру. Кубер будет искать ноды с этими ресурсами
              cpu: {{ .Values.grafana.resources.requests.cpu }}
              memory: {{ .Values.grafana.resources.requests.memory }}

      volumes:
        - name: datasources
          configMap:
            name: {{ include "avatargo.fullname" . }}-{{ .Values.grafana.component }}-cf
{{- end }}