{{- if .Values.rabbitmq.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "avatargo.fullname" . }}-{{ .Values.rabbitmq.component }}-scrt
  labels:
    {{- include "avatargo.labels" . | nindent 4 }}

data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc }}
type: Opaque
{{- end }}
