// Code generated by MockGen. DO NOT EDIT.
// Source: services.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qesterrx/AvatarGo/internal/models"
)

// MockMetaDB is a mock of MetaDB interface.
type MockMetaDB struct {
	ctrl     *gomock.Controller
	recorder *MockMetaDBMockRecorder
}

// MockMetaDBMockRecorder is the mock recorder for MockMetaDB.
type MockMetaDBMockRecorder struct {
	mock *MockMetaDB
}

// NewMockMetaDB creates a new mock instance.
func NewMockMetaDB(ctrl *gomock.Controller) *MockMetaDB {
	mock := &MockMetaDB{ctrl: ctrl}
	mock.recorder = &MockMetaDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaDB) EXPECT() *MockMetaDBMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockMetaDB) Check() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(string)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockMetaDBMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockMetaDB)(nil).Check))
}

// Create mocks base method.
func (m *MockMetaDB) Create(ctx context.Context, avatar *models.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMetaDBMockRecorder) Create(ctx, avatar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMetaDB)(nil).Create), ctx, avatar)
}

// Delete mocks base method.
func (m *MockMetaDB) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMetaDBMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMetaDB)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMetaDB) GetByID(ctx context.Context, id string) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMetaDBMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMetaDB)(nil).GetByID), ctx, id)
}

// MockFileDB is a mock of FileDB interface.
type MockFileDB struct {
	ctrl     *gomock.Controller
	recorder *MockFileDBMockRecorder
}

// MockFileDBMockRecorder is the mock recorder for MockFileDB.
type MockFileDBMockRecorder struct {
	mock *MockFileDB
}

// NewMockFileDB creates a new mock instance.
func NewMockFileDB(ctrl *gomock.Controller) *MockFileDB {
	mock := &MockFileDB{ctrl: ctrl}
	mock.recorder = &MockFileDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDB) EXPECT() *MockFileDBMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockFileDB) Check() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(string)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockFileDBMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockFileDB)(nil).Check))
}

// Del mocks base method.
func (m *MockFileDB) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockFileDBMockRecorder) Del(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockFileDB)(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockFileDB) Get(ctx context.Context, key string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockFileDBMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileDB)(nil).Get), ctx, key)
}

// GetURL mocks base method.
func (m *MockFileDB) GetURL(ctx context.Context, key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetURL indicates an expected call of GetURL.
func (mr *MockFileDBMockRecorder) GetURL(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockFileDB)(nil).GetURL), ctx, key)
}

// Put mocks base method.
func (m *MockFileDB) Put(ctx context.Context, key string, data []byte, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, data, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockFileDBMockRecorder) Put(ctx, key, data, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockFileDB)(nil).Put), ctx, key, data, contentType)
}

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockBroker) Check() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(string)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockBrokerMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockBroker)(nil).Check))
}

// PublishDeleteEvent mocks base method.
func (m *MockBroker) PublishDeleteEvent(ctx context.Context, event *models.AvatarDeleteEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeleteEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDeleteEvent indicates an expected call of PublishDeleteEvent.
func (mr *MockBrokerMockRecorder) PublishDeleteEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeleteEvent", reflect.TypeOf((*MockBroker)(nil).PublishDeleteEvent), ctx, event)
}

// PublishUnloadEvent mocks base method.
func (m *MockBroker) PublishUnloadEvent(ctx context.Context, event *models.AvatarUploadEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUnloadEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUnloadEvent indicates an expected call of PublishUnloadEvent.
func (mr *MockBrokerMockRecorder) PublishUnloadEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUnloadEvent", reflect.TypeOf((*MockBroker)(nil).PublishUnloadEvent), ctx, event)
}
