// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qesterrx/AvatarGo/internal/models"
)

// MockMetaDB is a mock of MetaDB interface.
type MockMetaDB struct {
	ctrl     *gomock.Controller
	recorder *MockMetaDBMockRecorder
}

// MockMetaDBMockRecorder is the mock recorder for MockMetaDB.
type MockMetaDBMockRecorder struct {
	mock *MockMetaDB
}

// NewMockMetaDB creates a new mock instance.
func NewMockMetaDB(ctrl *gomock.Controller) *MockMetaDB {
	mock := &MockMetaDB{ctrl: ctrl}
	mock.recorder = &MockMetaDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaDB) EXPECT() *MockMetaDBMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMetaDB) GetByID(ctx context.Context, id string) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMetaDBMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMetaDB)(nil).GetByID), ctx, id)
}

// UpdateThumbnails mocks base method.
func (m *MockMetaDB) UpdateThumbnails(ctx context.Context, id string, thumbnails models.ThumbnailKeys) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThumbnails", ctx, id, thumbnails)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThumbnails indicates an expected call of UpdateThumbnails.
func (mr *MockMetaDBMockRecorder) UpdateThumbnails(ctx, id, thumbnails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThumbnails", reflect.TypeOf((*MockMetaDB)(nil).UpdateThumbnails), ctx, id, thumbnails)
}

// MockFileDB is a mock of FileDB interface.
type MockFileDB struct {
	ctrl     *gomock.Controller
	recorder *MockFileDBMockRecorder
}

// MockFileDBMockRecorder is the mock recorder for MockFileDB.
type MockFileDBMockRecorder struct {
	mock *MockFileDB
}

// NewMockFileDB creates a new mock instance.
func NewMockFileDB(ctrl *gomock.Controller) *MockFileDB {
	mock := &MockFileDB{ctrl: ctrl}
	mock.recorder = &MockFileDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDB) EXPECT() *MockFileDBMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockFileDB) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockFileDBMockRecorder) Del(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockFileDB)(nil).Del), ctx, key)
}

// Exists mocks base method.
func (m *MockFileDB) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFileDBMockRecorder) Exists(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFileDB)(nil).Exists), ctx, key)
}

// Get mocks base method.
func (m *MockFileDB) Get(ctx context.Context, key string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockFileDBMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileDB)(nil).Get), ctx, key)
}

// Put mocks base method.
func (m *MockFileDB) Put(ctx context.Context, key string, data []byte, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, data, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockFileDBMockRecorder) Put(ctx, key, data, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockFileDB)(nil).Put), ctx, key, data, contentType)
}

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// GetChDeleteEvent mocks base method.
func (m *MockBroker) GetChDeleteEvent(ctx context.Context) (<-chan *models.AvatarDeleteEventHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChDeleteEvent", ctx)
	ret0, _ := ret[0].(<-chan *models.AvatarDeleteEventHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChDeleteEvent indicates an expected call of GetChDeleteEvent.
func (mr *MockBrokerMockRecorder) GetChDeleteEvent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChDeleteEvent", reflect.TypeOf((*MockBroker)(nil).GetChDeleteEvent), ctx)
}

// GetChUnloadEvent mocks base method.
func (m *MockBroker) GetChUnloadEvent(ctx context.Context) (<-chan *models.AvatarUploadEventHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChUnloadEvent", ctx)
	ret0, _ := ret[0].(<-chan *models.AvatarUploadEventHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChUnloadEvent indicates an expected call of GetChUnloadEvent.
func (mr *MockBrokerMockRecorder) GetChUnloadEvent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChUnloadEvent", reflect.TypeOf((*MockBroker)(nil).GetChUnloadEvent), ctx)
}
